
server:
  port: 9001
logging:
  file: log/log.log
  level:
    root: INFO
    com.haselt.softdevforum: INFO

spring:
  flyway:
    baseline-on-migrate: true
  servlet:
    ## Enable multipart uploads
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        ddl-auto: validate
    generate-ddl:  false
