#

logging:
  level:
    root: INFO
    com.haselt.softdevforum: DEBUG
    org.springframework.security: DEBUG
    org:
      hibernate:
        # Set Statistics level
        stat: debug
        SQL: debug
        type:
          descriptor:
            sql: trace

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/softdevforum
    username: softdevforum
    password: softdevforum@haselt
    testWhileIdle: true
    validationQuery: SELECT 1 #check what this does
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      generate-ddl: false
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    #Turn Statistics on
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        generate_statistics: true